add matrix strategy

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -13,11 +13,29 @@ jobs:
   #   uses: ./.github/workflows/get_docs_changes.yml
 
   run_lint:
-    name: Runs mypy, flake and bandit
+    name: Runs make lint
     # needs: get_docs_changes
     # if: needs.get_docs_changes.outputs.changes_outside_docs == 'true'
+    strategy:
+      fail-fast: false
+      matrix:
+        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
+        python-version: ["3.11.x"]
+        # Test all python versions on ubuntu only
+        include:
+          - python-version: "3.8.x"
+            os: "ubuntu-latest"
+          - python-version: "3.9.x"
+            os: "ubuntu-latest"
+          - python-version: "3.10.x"
+            os: "ubuntu-latest"
 
-    runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash
+    runs-on: ${{ matrix.os }}    
+
+    # runs-on: ubuntu-latest
 
     steps:
 
@@ -58,3 +76,14 @@ jobs:
       #     echo "The GitHub Actor's username is: $GITHUB_ACTOR"
       #     echo "The GitHub repo owner is: $GITHUB_REPOSITORY_OWNER"
       #     echo "The GitHub repo is: $GITHUB_REPOSITORY"
+
+  matrix_job_required_check:
+    name: Lint results
+    needs: run_lint
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+      - name: Check matrix job results
+        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
+        run: |
+          echo "One or more matrix job tests failed or were cancelled. You may need to re-run them." && exit 1      
