Fix Windows lint issue and implement CI lint matrix strategy (#827)
* adjusted black exclude logic

* comment job for testing purpopes

* add matrix strategy

* install make on Windows runner

* move make install up

* specify bash shell

* python-version assignment

* comment

* check poetry install

* poetry shell command

* echo PATH var

* echo $GITHUB_PATH

* check make install

* check poetry install

* comment make install

* pwsh

* echo commands

* show make shell

* list dir

* ls

* ls

* echo $PATH

* extend path

* windows python matrix

* extend PATH

* upgrade connectorx

* reversed connectorx upgrade

* extended matrix

* PATH extension

* PATH extension

* cached venv key

* cached venv key

* removed debugging statement

* uncomment step

---------

Co-authored-by: Jorrit Sandbrink <sandbj01@heiway.net>

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -13,11 +13,19 @@ jobs:
     uses: ./.github/workflows/get_docs_changes.yml
 
   run_lint:
-    name: Runs mypy, flake and bandit
+    name: Lint
     needs: get_docs_changes
     if: needs.get_docs_changes.outputs.changes_outside_docs == 'true'
+    strategy:
+      fail-fast: false
+      matrix:
+        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
+        python-version: ["3.8.x", "3.9.x", "3.10.x", "3.11.x"]
 
-    runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash
+    runs-on: ${{ matrix.os }}    
 
     steps:
 
@@ -27,34 +35,46 @@ jobs:
       - name: Setup Python
         uses: actions/setup-python@v4
         with:
-          python-version: "3.10.x"
+          python-version: ${{ matrix.python-version }}
 
       - name: Install Poetry
         uses: snok/install-poetry@v1
         with:
           virtualenvs-create: true
           virtualenvs-in-project: true
-          installer-parallel: true
+          installer-parallel: true         
 
       - name: Load cached venv
         id: cached-poetry-dependencies
         uses: actions/cache@v3
         with:
           path: .venv
-          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
+          key: venv-${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
 
-      - name: Install dependencies
+      - name: Run make dev
         # if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
-        run: poetry install --no-interaction --all-extras --with airflow --with docs --with providers --with sentry-sdk --with pipeline
+        run: |
+          export PATH=$PATH:"/c/Program Files/usr/bin" # needed for Windows      
+          make dev
 
-      # - name: Install self
-      #   run: poetry install --no-interaction
-
-      - name: Run lint
-        run: make lint
+      - name: Run make lint
+        run: |
+          export PATH=$PATH:"/c/Program Files/usr/bin" # needed for Windows        
+          make lint
 
       # - name: print envs
       #   run: |
       #     echo "The GitHub Actor's username is: $GITHUB_ACTOR"
       #     echo "The GitHub repo owner is: $GITHUB_REPOSITORY_OWNER"
       #     echo "The GitHub repo is: $GITHUB_REPOSITORY"
+
+  matrix_job_required_check:
+    name: Lint results
+    needs: run_lint
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+      - name: Check matrix job results
+        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
+        run: |
+          echo "One or more matrix job tests failed or were cancelled. You may need to re-run them." && exit 1      
